/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as authLayoutTrashRouteImport } from './routes/(auth)/_layout/trash'
import { Route as authLayoutSettingsRouteImport } from './routes/(auth)/_layout/settings'
import { Route as authLayoutNotificationsRouteImport } from './routes/(auth)/_layout/notifications'
import { Route as authLayoutLogoutRouteImport } from './routes/(auth)/_layout/logout'
import { Route as authLayoutFavoritesRouteImport } from './routes/(auth)/_layout/favorites'
import { Route as authLayoutDashboardRouteImport } from './routes/(auth)/_layout/dashboard'
import { Route as authLayoutProjectsIndexRouteImport } from './routes/(auth)/_layout/projects/index'
import { Route as authLayoutDocumentsIndexRouteImport } from './routes/(auth)/_layout/documents/index'
import { Route as authLayoutProjectsProjectIdRouteImport } from './routes/(auth)/_layout/projects/$projectId'
import { Route as authLayoutDocumentsDocIdIndexRouteImport } from './routes/(auth)/_layout/documents/$docId/index'
import { Route as authLayoutDocumentsDocIdVersionsRouteImport } from './routes/(auth)/_layout/documents/$docId/versions'
import { Route as authLayoutDocumentsDocIdHistoryRouteImport } from './routes/(auth)/_layout/documents/$docId/history'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutTrashRoute = authLayoutTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutSettingsRoute = authLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutNotificationsRoute = authLayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutLogoutRoute = authLayoutLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutFavoritesRoute = authLayoutFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutDashboardRoute = authLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutProjectsIndexRoute = authLayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutDocumentsIndexRoute =
  authLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutProjectsProjectIdRoute =
  authLayoutProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDocumentsDocIdIndexRoute =
  authLayoutDocumentsDocIdIndexRouteImport.update({
    id: '/documents/$docId/',
    path: '/documents/$docId/',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDocumentsDocIdVersionsRoute =
  authLayoutDocumentsDocIdVersionsRouteImport.update({
    id: '/documents/$docId/versions',
    path: '/documents/$docId/versions',
    getParentRoute: () => authLayoutRoute,
  } as any)
const authLayoutDocumentsDocIdHistoryRoute =
  authLayoutDocumentsDocIdHistoryRouteImport.update({
    id: '/documents/$docId/history',
    path: '/documents/$docId/history',
    getParentRoute: () => authLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authLayoutDashboardRoute
  '/favorites': typeof authLayoutFavoritesRoute
  '/logout': typeof authLayoutLogoutRoute
  '/notifications': typeof authLayoutNotificationsRoute
  '/settings': typeof authLayoutSettingsRoute
  '/trash': typeof authLayoutTrashRoute
  '/projects/$projectId': typeof authLayoutProjectsProjectIdRoute
  '/documents': typeof authLayoutDocumentsIndexRoute
  '/projects': typeof authLayoutProjectsIndexRoute
  '/documents/$docId/history': typeof authLayoutDocumentsDocIdHistoryRoute
  '/documents/$docId/versions': typeof authLayoutDocumentsDocIdVersionsRoute
  '/documents/$docId': typeof authLayoutDocumentsDocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authLayoutDashboardRoute
  '/favorites': typeof authLayoutFavoritesRoute
  '/logout': typeof authLayoutLogoutRoute
  '/notifications': typeof authLayoutNotificationsRoute
  '/settings': typeof authLayoutSettingsRoute
  '/trash': typeof authLayoutTrashRoute
  '/projects/$projectId': typeof authLayoutProjectsProjectIdRoute
  '/documents': typeof authLayoutDocumentsIndexRoute
  '/projects': typeof authLayoutProjectsIndexRoute
  '/documents/$docId/history': typeof authLayoutDocumentsDocIdHistoryRoute
  '/documents/$docId/versions': typeof authLayoutDocumentsDocIdVersionsRoute
  '/documents/$docId': typeof authLayoutDocumentsDocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/dashboard': typeof authLayoutDashboardRoute
  '/(auth)/_layout/favorites': typeof authLayoutFavoritesRoute
  '/(auth)/_layout/logout': typeof authLayoutLogoutRoute
  '/(auth)/_layout/notifications': typeof authLayoutNotificationsRoute
  '/(auth)/_layout/settings': typeof authLayoutSettingsRoute
  '/(auth)/_layout/trash': typeof authLayoutTrashRoute
  '/(auth)/_layout/projects/$projectId': typeof authLayoutProjectsProjectIdRoute
  '/(auth)/_layout/documents/': typeof authLayoutDocumentsIndexRoute
  '/(auth)/_layout/projects/': typeof authLayoutProjectsIndexRoute
  '/(auth)/_layout/documents/$docId/history': typeof authLayoutDocumentsDocIdHistoryRoute
  '/(auth)/_layout/documents/$docId/versions': typeof authLayoutDocumentsDocIdVersionsRoute
  '/(auth)/_layout/documents/$docId/': typeof authLayoutDocumentsDocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/dashboard'
    | '/favorites'
    | '/logout'
    | '/notifications'
    | '/settings'
    | '/trash'
    | '/projects/$projectId'
    | '/documents'
    | '/projects'
    | '/documents/$docId/history'
    | '/documents/$docId/versions'
    | '/documents/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/dashboard'
    | '/favorites'
    | '/logout'
    | '/notifications'
    | '/settings'
    | '/trash'
    | '/projects/$projectId'
    | '/documents'
    | '/projects'
    | '/documents/$docId/history'
    | '/documents/$docId/versions'
    | '/documents/$docId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/(auth)/_layout'
    | '/(auth)/_layout/dashboard'
    | '/(auth)/_layout/favorites'
    | '/(auth)/_layout/logout'
    | '/(auth)/_layout/notifications'
    | '/(auth)/_layout/settings'
    | '/(auth)/_layout/trash'
    | '/(auth)/_layout/projects/$projectId'
    | '/(auth)/_layout/documents/'
    | '/(auth)/_layout/projects/'
    | '/(auth)/_layout/documents/$docId/history'
    | '/(auth)/_layout/documents/$docId/versions'
    | '/(auth)/_layout/documents/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/trash': {
      id: '/(auth)/_layout/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof authLayoutTrashRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/settings': {
      id: '/(auth)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authLayoutSettingsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/notifications': {
      id: '/(auth)/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof authLayoutNotificationsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/logout': {
      id: '/(auth)/_layout/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLayoutLogoutRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/favorites': {
      id: '/(auth)/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof authLayoutFavoritesRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard': {
      id: '/(auth)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authLayoutDashboardRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/projects/': {
      id: '/(auth)/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authLayoutProjectsIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/documents/': {
      id: '/(auth)/_layout/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof authLayoutDocumentsIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/projects/$projectId': {
      id: '/(auth)/_layout/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof authLayoutProjectsProjectIdRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/documents/$docId/': {
      id: '/(auth)/_layout/documents/$docId/'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof authLayoutDocumentsDocIdIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/documents/$docId/versions': {
      id: '/(auth)/_layout/documents/$docId/versions'
      path: '/documents/$docId/versions'
      fullPath: '/documents/$docId/versions'
      preLoaderRoute: typeof authLayoutDocumentsDocIdVersionsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/documents/$docId/history': {
      id: '/(auth)/_layout/documents/$docId/history'
      path: '/documents/$docId/history'
      fullPath: '/documents/$docId/history'
      preLoaderRoute: typeof authLayoutDocumentsDocIdHistoryRouteImport
      parentRoute: typeof authLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutDashboardRoute: typeof authLayoutDashboardRoute
  authLayoutFavoritesRoute: typeof authLayoutFavoritesRoute
  authLayoutLogoutRoute: typeof authLayoutLogoutRoute
  authLayoutNotificationsRoute: typeof authLayoutNotificationsRoute
  authLayoutSettingsRoute: typeof authLayoutSettingsRoute
  authLayoutTrashRoute: typeof authLayoutTrashRoute
  authLayoutProjectsProjectIdRoute: typeof authLayoutProjectsProjectIdRoute
  authLayoutDocumentsIndexRoute: typeof authLayoutDocumentsIndexRoute
  authLayoutProjectsIndexRoute: typeof authLayoutProjectsIndexRoute
  authLayoutDocumentsDocIdHistoryRoute: typeof authLayoutDocumentsDocIdHistoryRoute
  authLayoutDocumentsDocIdVersionsRoute: typeof authLayoutDocumentsDocIdVersionsRoute
  authLayoutDocumentsDocIdIndexRoute: typeof authLayoutDocumentsDocIdIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutDashboardRoute: authLayoutDashboardRoute,
  authLayoutFavoritesRoute: authLayoutFavoritesRoute,
  authLayoutLogoutRoute: authLayoutLogoutRoute,
  authLayoutNotificationsRoute: authLayoutNotificationsRoute,
  authLayoutSettingsRoute: authLayoutSettingsRoute,
  authLayoutTrashRoute: authLayoutTrashRoute,
  authLayoutProjectsProjectIdRoute: authLayoutProjectsProjectIdRoute,
  authLayoutDocumentsIndexRoute: authLayoutDocumentsIndexRoute,
  authLayoutProjectsIndexRoute: authLayoutProjectsIndexRoute,
  authLayoutDocumentsDocIdHistoryRoute: authLayoutDocumentsDocIdHistoryRoute,
  authLayoutDocumentsDocIdVersionsRoute: authLayoutDocumentsDocIdVersionsRoute,
  authLayoutDocumentsDocIdIndexRoute: authLayoutDocumentsDocIdIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
