/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLayoutRouteImport } from './routes/(auth)/_layout'
import { Route as authLayoutTrashRouteImport } from './routes/(auth)/_layout/trash'
import { Route as authLayoutSettingsRouteImport } from './routes/(auth)/_layout/settings'
import { Route as authLayoutProjectsRouteImport } from './routes/(auth)/_layout/projects'
import { Route as authLayoutNotificationsRouteImport } from './routes/(auth)/_layout/notifications'
import { Route as authLayoutLogoutRouteImport } from './routes/(auth)/_layout/logout'
import { Route as authLayoutFavoritesRouteImport } from './routes/(auth)/_layout/favorites'
import { Route as authLayoutDocumentsRouteImport } from './routes/(auth)/_layout/documents'
import { Route as authLayoutDashboardRouteImport } from './routes/(auth)/_layout/dashboard'
import { Route as authDocsDocIdIndexRouteImport } from './routes/(auth)/docs/$docId/index'
import { Route as authDocsDocIdVersionsRouteImport } from './routes/(auth)/docs/$docId/versions'
import { Route as authDocsDocIdHistoryRouteImport } from './routes/(auth)/docs/$docId/history'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutTrashRoute = authLayoutTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutSettingsRoute = authLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutProjectsRoute = authLayoutProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutNotificationsRoute = authLayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutLogoutRoute = authLayoutLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutFavoritesRoute = authLayoutFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutDocumentsRoute = authLayoutDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLayoutDashboardRoute = authLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authLayoutRoute,
} as any)
const authDocsDocIdIndexRoute = authDocsDocIdIndexRouteImport.update({
  id: '/(auth)/docs/$docId/',
  path: '/docs/$docId/',
  getParentRoute: () => rootRouteImport,
} as any)
const authDocsDocIdVersionsRoute = authDocsDocIdVersionsRouteImport.update({
  id: '/(auth)/docs/$docId/versions',
  path: '/docs/$docId/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const authDocsDocIdHistoryRoute = authDocsDocIdHistoryRouteImport.update({
  id: '/(auth)/docs/$docId/history',
  path: '/docs/$docId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authLayoutDashboardRoute
  '/documents': typeof authLayoutDocumentsRoute
  '/favorites': typeof authLayoutFavoritesRoute
  '/logout': typeof authLayoutLogoutRoute
  '/notifications': typeof authLayoutNotificationsRoute
  '/projects': typeof authLayoutProjectsRoute
  '/settings': typeof authLayoutSettingsRoute
  '/trash': typeof authLayoutTrashRoute
  '/docs/$docId/history': typeof authDocsDocIdHistoryRoute
  '/docs/$docId/versions': typeof authDocsDocIdVersionsRoute
  '/docs/$docId': typeof authDocsDocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof authLayoutDashboardRoute
  '/documents': typeof authLayoutDocumentsRoute
  '/favorites': typeof authLayoutFavoritesRoute
  '/logout': typeof authLayoutLogoutRoute
  '/notifications': typeof authLayoutNotificationsRoute
  '/projects': typeof authLayoutProjectsRoute
  '/settings': typeof authLayoutSettingsRoute
  '/trash': typeof authLayoutTrashRoute
  '/docs/$docId/history': typeof authDocsDocIdHistoryRoute
  '/docs/$docId/versions': typeof authDocsDocIdVersionsRoute
  '/docs/$docId': typeof authDocsDocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/(auth)/_layout/dashboard': typeof authLayoutDashboardRoute
  '/(auth)/_layout/documents': typeof authLayoutDocumentsRoute
  '/(auth)/_layout/favorites': typeof authLayoutFavoritesRoute
  '/(auth)/_layout/logout': typeof authLayoutLogoutRoute
  '/(auth)/_layout/notifications': typeof authLayoutNotificationsRoute
  '/(auth)/_layout/projects': typeof authLayoutProjectsRoute
  '/(auth)/_layout/settings': typeof authLayoutSettingsRoute
  '/(auth)/_layout/trash': typeof authLayoutTrashRoute
  '/(auth)/docs/$docId/history': typeof authDocsDocIdHistoryRoute
  '/(auth)/docs/$docId/versions': typeof authDocsDocIdVersionsRoute
  '/(auth)/docs/$docId/': typeof authDocsDocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/dashboard'
    | '/documents'
    | '/favorites'
    | '/logout'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/trash'
    | '/docs/$docId/history'
    | '/docs/$docId/versions'
    | '/docs/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/dashboard'
    | '/documents'
    | '/favorites'
    | '/logout'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/trash'
    | '/docs/$docId/history'
    | '/docs/$docId/versions'
    | '/docs/$docId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/recover'
    | '/signup'
    | '/(auth)/_layout'
    | '/(auth)/_layout/dashboard'
    | '/(auth)/_layout/documents'
    | '/(auth)/_layout/favorites'
    | '/(auth)/_layout/logout'
    | '/(auth)/_layout/notifications'
    | '/(auth)/_layout/projects'
    | '/(auth)/_layout/settings'
    | '/(auth)/_layout/trash'
    | '/(auth)/docs/$docId/history'
    | '/(auth)/docs/$docId/versions'
    | '/(auth)/docs/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  authDocsDocIdHistoryRoute: typeof authDocsDocIdHistoryRoute
  authDocsDocIdVersionsRoute: typeof authDocsDocIdVersionsRoute
  authDocsDocIdIndexRoute: typeof authDocsDocIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_layout/trash': {
      id: '/(auth)/_layout/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof authLayoutTrashRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/settings': {
      id: '/(auth)/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authLayoutSettingsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/projects': {
      id: '/(auth)/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof authLayoutProjectsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/notifications': {
      id: '/(auth)/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof authLayoutNotificationsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/logout': {
      id: '/(auth)/_layout/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof authLayoutLogoutRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/favorites': {
      id: '/(auth)/_layout/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof authLayoutFavoritesRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/documents': {
      id: '/(auth)/_layout/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof authLayoutDocumentsRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/_layout/dashboard': {
      id: '/(auth)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authLayoutDashboardRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/docs/$docId/': {
      id: '/(auth)/docs/$docId/'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof authDocsDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/docs/$docId/versions': {
      id: '/(auth)/docs/$docId/versions'
      path: '/docs/$docId/versions'
      fullPath: '/docs/$docId/versions'
      preLoaderRoute: typeof authDocsDocIdVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/docs/$docId/history': {
      id: '/(auth)/docs/$docId/history'
      path: '/docs/$docId/history'
      fullPath: '/docs/$docId/history'
      preLoaderRoute: typeof authDocsDocIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authLayoutRouteChildren {
  authLayoutDashboardRoute: typeof authLayoutDashboardRoute
  authLayoutDocumentsRoute: typeof authLayoutDocumentsRoute
  authLayoutFavoritesRoute: typeof authLayoutFavoritesRoute
  authLayoutLogoutRoute: typeof authLayoutLogoutRoute
  authLayoutNotificationsRoute: typeof authLayoutNotificationsRoute
  authLayoutProjectsRoute: typeof authLayoutProjectsRoute
  authLayoutSettingsRoute: typeof authLayoutSettingsRoute
  authLayoutTrashRoute: typeof authLayoutTrashRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutDashboardRoute: authLayoutDashboardRoute,
  authLayoutDocumentsRoute: authLayoutDocumentsRoute,
  authLayoutFavoritesRoute: authLayoutFavoritesRoute,
  authLayoutLogoutRoute: authLayoutLogoutRoute,
  authLayoutNotificationsRoute: authLayoutNotificationsRoute,
  authLayoutProjectsRoute: authLayoutProjectsRoute,
  authLayoutSettingsRoute: authLayoutSettingsRoute,
  authLayoutTrashRoute: authLayoutTrashRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  authDocsDocIdHistoryRoute: authDocsDocIdHistoryRoute,
  authDocsDocIdVersionsRoute: authDocsDocIdVersionsRoute,
  authDocsDocIdIndexRoute: authDocsDocIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
